version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  node-monitor-net:


services:
  indy-node-monitor:
    image: ${DOCKER_REGISTRY_SERVER_URL}/indy-node-monitor-${ENVIONMENT}:latest
    volumes:
      - ./fetch-validator-status/plugins/:/home/indy/plugins/
      - ./fetch-validator-status/conf/:/home/indy/conf/
      - ./fetch-validator-status/logs/:/home/indy/logs/
    ports:
      - "8080:8080"
    networks:
      - node-monitor-net
    command: >
      --web --verbose

  telegraf:
    image: telegraf:latest
    env_file:
      - ${TELEGRAF_ENV}
    links:
      - influxdb
      - indy-node-monitor
    volumes:
      - ${WEBAPP_STORAGE_HOME}/telegraf/:/etc/telegraf/
    depends_on:
      - influxdb
      - indy-node-monitor
    ports:
      - "9273:9273"
    networks:
      - node-monitor-net

  influxdb:
    image: influxdb:latest
    volumes:
      - ${WEBAPP_STORAGE_HOME}/influxdb/data:/var/lib/influxdb
      - ${WEBAPP_STORAGE_HOME}/influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"
    networks:
      - node-monitor-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ${WEBAPP_STORAGE_HOME}/prometheus/:/etc/prometheus/
      - ${WEBAPP_STORAGE_HOME}/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - telegraf
      - alertmanager
    depends_on:
      - telegraf
    networks:
      - node-monitor-net

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "${WEBAPP_STORAGE_HOME}/alertmanager/:/etc/alertmanager/"
    networks:
      - node-monitor-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    volumes:
      - ${WEBAPP_STORAGE_HOME}/grafana/grafana_data:/var/lib/grafana
      - ${WEBAPP_STORAGE_HOME}/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ${GRAFANA_ENV}
    networks:
      - node-monitor-net
    links:
      - influxdb
      - prometheus
    user: "472"
