version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  node-monitor-net:


services:
  indy-node-monitor:
    build:
      context: ./fetch-validator-status
      dockerfile: ./Dockerfile
    image: indy-node-monitor
    volumes:
      - ./fetch-validator-status/plugins/:/home/indy/plugins/
      - ./fetch-validator-status/conf/:/home/indy/conf/
      - ./fetch-validator-status/logs/:/home/indy/logs/
    ports:
      - "8080:8080"
    networks:
      - node-monitor-net
    command: >
      --web --verbose

  telegraf:
    build:
      context: ./images/telegraf/
      dockerfile: ./${TYPE}/Dockerfile
      args:
        TELEGRAF_TAG: ${TELEGRAF_TAG}
    image: telegraf
    env_file:
      - ${TELEGRAF_ENV}
    links:
      - influxdb
      - indy-node-monitor
    volumes:
      - ./telegraf/:/etc/telegraf/
    depends_on:
      - influxdb
      - indy-node-monitor
    ports:
      - "9273:9273"
    networks:
      - node-monitor-net

  influxdb:
    build:
      context: ./images/influxdb/
      dockerfile: ./${TYPE}/Dockerfile
      args:
        INFLUXDB_TAG: ${INFLUXDB_TAG}
    image: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"
    networks:
      - node-monitor-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - telegraf
      - alertmanager
    depends_on:
      - telegraf
    networks:
      - node-monitor-net

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    networks:
      - node-monitor-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    build:
      context: ./images/grafana/
      dockerfile: ./Dockerfile
      args:
        GRAFANA_TAG: ${GRAFANA_TAG}
    image: grafana
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ${GRAFANA_ENV}
    networks:
      - node-monitor-net
    links:
      - influxdb
      - prometheus
    user: "472"
